create-custom-button
KrolMateusz/praktyki1 pull request #17
Opened 2021-06-24 11:58 UTC by web-lizzard

2021-06-24 13:35 UTC, tomasz-commerce requested changes

2021-06-24 13:35 UTC, tomasz-commerce commented on src/components/common/Button.vue
> +      const classes = [];
no ok, ale zmieściło by się to w htmlu na 
`:class = 
{ 'px-40': isBig,
'bg-warning text-gray-900': isWarning
 }
`
ma to taką zaletę, że trzymasz css razem z htmlem a nie mieszasz go z jsem, tzn wszystko jest w dedykowanym dla siebie miejscu w kodzie

2021-06-24 17:17 UTC, tomasz-commerce approved these changes

2021-06-25 07:13 UTC, KrolMateusz approved these changes

2021-06-25 07:17 UTC, dudeek approved these changes

2021-06-25 07:17 UTC, merged