fix clear route
KrolMateusz/praktyki1 pull request #47
Opened 2021-07-06 13:02 UTC by web-lizzard

2021-07-06 13:34 UTC, dudeek approved these changes

2021-07-07 09:28 UTC, KrolMateusz approved these changes

2021-07-07 11:44 UTC, foxy-methoxy requested changes

2021-07-07 11:44 UTC, foxy-methoxy commented on src/components/Form.vue
> +    const foodType = computed(() => store.getters.getFoodTypeId);
foodTypeId, jak wszedzie jest id

2021-07-07 11:44 UTC, foxy-methoxy commented on src/components/Form.vue
> +        name="group1"
a group2 to co by to bylo?

2021-07-08 08:02 UTC, foxy-methoxy approved these changes

2021-07-08 08:02 UTC, merged