praktyki1-005 profile
KrolMateusz/praktyki1 pull request #9
Opened 2021-06-22 08:35 UTC by dudeek

2021-06-22 12:51 UTC, mnieznaj requested changes
to nie miało być domergowane do deva?

2021-06-24 17:33 UTC, tomasz-commerce requested changes

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/common/Profile.vue
> +    const getFFMI = computed(() => (props.weight * 0.83).toFixed(2));
a to nie jest tak, że potrzeba % tkanki tłuszczowej do wyznaczenia FFMI? :D chyba jest jeszcze jeden input potrzebny, proponuję opcjonalny bo mało kto umie, lub ma sprzęt żeby sobie zmierzyć 

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/home/Home.vue
> +        :surname="surname"
lastname, surname to na brytyjskim dworze używają

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/home/Home.vue
>  // @ is an alias to /src
usun zbędne komcie

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/home/Home.vue
> +import Profile from "../common/Profile.vue";
importy przez `@`

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/common/Profile.vue
> +import Avatar from "./Avatar.vue";
`@`

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/common/Profile.vue
> +        Waga: <span class="font-semibold">{{ weight }} kg</span>
z tego co widziałem designy to user jest w stanie zmienić sobie jednostkę profilu, więc to nie powinno być statyczne. zapisz najlepiej do stora jakich używa, może jakiś mały komponent co automatycznie konwertuje

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/common/Profile.vue
> +    const getName = computed(() => props.name.capitalize);
to są w gruncie rzeczy zmienne, a nie funkcje - unikaj nazywania ich z przedrostkiem get, bo one nic nie pobierają, tylko zwracają dane. niech lepiej opisują swoją zawartość, bardziej coś na zasadzie userName

2021-06-24 17:33 UTC, tomasz-commerce commented on src/components/common/Profile.vue
> +    fasttemp: {
camelcasem nazwy zmiennych. nie musisz też oszczędzać na bitach ucinając części słów :P i tak podczas kompilacji na proda wszystko zostanie obscurifikowane 
`fastTempo` będzie optymalnie

2021-06-25 09:17 UTC, Vearso commented on src/components/common/Profile.vue
> +          :firstName="name"
kolejność atrybutów

2021-06-25 09:17 UTC, Vearso commented on src/components/common/Profile.vue
> +  props: {
Jeżli te propsy są pobierane ze store, to przekazujesz je przez dwa komponenty, możesz je zdefiniować w tym komponencie, przynajmniej część

2021-06-25 09:17 UTC, Vearso commented on src/components/home/Home.vue
> +        :name="name"
kolejność atrybutów

2021-06-25 09:17 UTC, Vearso commented on src/components/home/Home.vue
> +import { ref } from "vue";
Bezpośrednie importy z bibliotek na samą górę

2021-06-25 09:17 UTC, Vearso commented on src/components/common/Avatar.vue
>        v-if="getImage"
kolejność atrybutów

2021-06-25 09:30 UTC, mnieznaj commented on src/components/home/Home.vue
> +    const FFMI = ref();
jeśli ma być pusty to wpisz null

2021-06-25 11:11 UTC, Vearso approved these changes

2021-06-25 11:44 UTC, web-lizzard approved these changes

2021-06-25 11:52 UTC, KrolMateusz approved these changes

2021-06-25 11:53 UTC, merged